// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRNIPyh8ufQ6a6q36cCwrnvkORVZ4_Po',
    appId: '1:681696689269:web:552cd0c2f7f2ebcf2d4c3c',
    messagingSenderId: '681696689269',
    projectId: 'muzk-project',
    authDomain: 'muzk-project.firebaseapp.com',
    storageBucket: 'muzk-project.appspot.com',
    measurementId: 'G-RPPME0R5GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPBhcT8A6kywbDSMXdQmoSi9rRMIufHI',
    appId: '1:681696689269:android:6005939accd868442d4c3c',
    messagingSenderId: '681696689269',
    projectId: 'muzk-project',
    storageBucket: 'muzk-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNelZG7dbxMGc8dUmrTVjAVFe8xU683M',
    appId: '1:681696689269:ios:a91c464395e876cb2d4c3c',
    messagingSenderId: '681696689269',
    projectId: 'muzk-project',
    storageBucket: 'muzk-project.appspot.com',
    iosClientId: '681696689269-b5m8r61raomhv10ch0j1ma2b4hjcetil.apps.googleusercontent.com',
    iosBundleId: 'com.example.muzk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNelZG7dbxMGc8dUmrTVjAVFe8xU683M',
    appId: '1:681696689269:ios:a91c464395e876cb2d4c3c',
    messagingSenderId: '681696689269',
    projectId: 'muzk-project',
    storageBucket: 'muzk-project.appspot.com',
    iosClientId: '681696689269-b5m8r61raomhv10ch0j1ma2b4hjcetil.apps.googleusercontent.com',
    iosBundleId: 'com.example.muzk',
  );
}
